spring.application.name=TaskApp
server.port=${PORT:3030}

# --- H2 DATABASE CONFIG ---
spring.datasource.url=jdbc:h2:mem:tasksdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

# --- EMAIL REMINDER CONFIGURATION ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# --- SCHEDULING (Required for @Scheduled tasks) ---
spring.task.scheduling.pool.size=5

spring.main.allow-bean-definition-overriding=true

spring.mvc.cors.allowed-origins=http://localhost:3000

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.filter.CorsFilter=TRACE
logging.level.org.springframework.security.web.FilterChainProxy=TRACE